SELECT * 
FROM classicmodels.employees
 WHERE  UPPER(Email) IN 
( 'PMARSH@CLASSICMODELCARS.COM', 
'GBONDUR@CLASSICMODELCARS.COM', 
'ABOW@CLASSICMODELCARS.COM');
 
 SELECT * 
FROM classicmodels.employees
 WHERE  UPPER(Email)  NOT IN 
( 'PMARSH@CLASSICMODELCARS.COM', 
'GBONDUR@CLASSICMODELCARS.COM', 
'ABOW@CLASSICMODELCARS.COM');