 SELECT *
 FROM
 (SELECT ORDERDATE,  COUNT(ORDERNUMBER) AS ORDERS FROM CLASSICMODELS.ORDERS
 GROUP BY ORDERDATE) t1;
 
 SELECT AVG(ORDERS)
 FROM
 (SELECT ORDERDATE,  COUNT(ORDERNUMBER) AS ORDERS FROM CLASSICMODELS.ORDERS
 GROUP BY ORDERDATE) t1;